/* Generated by Frama-C */
#include "pthread.h"
#include "sched.h"
#include "signal.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "time.h"
struct __e_acsl_mpz_struct {
   int _mp_alloc ;
   int _mp_size ;
   unsigned long *_mp_d ;
};
typedef struct __e_acsl_mpz_struct __e_acsl_mpz_struct;
typedef __e_acsl_mpz_struct ( __attribute__((__FC_BUILTIN__)) __e_acsl_mpz_t)[1];
struct __e_acsl_mpq_struct {
   __e_acsl_mpz_struct _mp_num ;
   __e_acsl_mpz_struct _mp_den ;
};
typedef struct __e_acsl_mpq_struct __e_acsl_mpq_struct;
typedef __e_acsl_mpq_struct ( __attribute__((__FC_BUILTIN__)) __e_acsl_mpq_t)[1];
typedef unsigned long __e_acsl_mp_bitcnt_t;
enum __e_acsl_assert_data_type_t {
    E_ACSL_INT = 0,
    E_ACSL_REAL = 1,
    E_ACSL_PTR = 2,
    E_ACSL_ARRAY = 3,
    E_ACSL_FUN = 4,
    E_ACSL_STRUCT = 5,
    E_ACSL_UNION = 6,
    E_ACSL_OTHER = 1000
};
typedef enum __e_acsl_assert_data_type_t __attribute__((__FC_BUILTIN__)) __e_acsl_assert_data_type_t;
enum __e_acsl_assert_data_ikind_t {
    E_ACSL_IBOOL = 0,
    E_ACSL_ICHAR = 1,
    E_ACSL_ISCHAR = 2,
    E_ACSL_IUCHAR = 3,
    E_ACSL_IINT = 4,
    E_ACSL_IUINT = 5,
    E_ACSL_ISHORT = 6,
    E_ACSL_IUSHORT = 7,
    E_ACSL_ILONG = 8,
    E_ACSL_IULONG = 9,
    E_ACSL_ILONGLONG = 10,
    E_ACSL_IULONGLONG = 11,
    E_ACSL_IMPZ = 12
};
typedef enum __e_acsl_assert_data_ikind_t __attribute__((__FC_BUILTIN__)) __e_acsl_assert_data_ikind_t;
enum __e_acsl_assert_data_rkind_t {
    E_ACSL_RFLOAT = 0,
    E_ACSL_RDOUBLE = 1,
    E_ACSL_RLONGDOUBLE = 2,
    E_ACSL_RMPQ = 3
};
typedef enum __e_acsl_assert_data_rkind_t __attribute__((__FC_BUILTIN__)) __e_acsl_assert_data_rkind_t;
union __e_acsl_assert_data_int_value_t {
   _Bool value_bool ;
   char value_char ;
   signed char value_schar ;
   unsigned char value_uchar ;
   int value_int ;
   unsigned int value_uint ;
   short value_short ;
   unsigned short value_ushort ;
   long value_long ;
   unsigned long value_ulong ;
   long long value_llong ;
   unsigned long long value_ullong ;
   struct __e_acsl_mpz_struct *value_mpz ;
};
typedef union __e_acsl_assert_data_int_value_t __attribute__((__FC_BUILTIN__)) __e_acsl_assert_data_int_value_t;
union __e_acsl_assert_data_real_value_t {
   float value_float ;
   double value_double ;
   long double value_ldouble ;
   struct __e_acsl_mpq_struct *value_mpq ;
};
typedef union __e_acsl_assert_data_real_value_t __attribute__((__FC_BUILTIN__)) __e_acsl_assert_data_real_value_t;
struct __e_acsl_assert_data_int_content_t {
   int is_enum ;
   __e_acsl_assert_data_ikind_t kind ;
   __e_acsl_assert_data_int_value_t value ;
};
typedef struct __e_acsl_assert_data_int_content_t __attribute__((__FC_BUILTIN__)) __e_acsl_assert_data_int_content_t;
struct __e_acsl_assert_data_real_content_t {
   __e_acsl_assert_data_rkind_t kind ;
   __e_acsl_assert_data_real_value_t value ;
};
typedef struct __e_acsl_assert_data_real_content_t __attribute__((__FC_BUILTIN__)) __e_acsl_assert_data_real_content_t;
union __e_acsl_assert_data_content_t {
   __e_acsl_assert_data_int_content_t int_content ;
   __e_acsl_assert_data_real_content_t real_content ;
   uintptr_t value_ptr ;
   uintptr_t value_array ;
};
typedef union __e_acsl_assert_data_content_t __attribute__((__FC_BUILTIN__)) __e_acsl_assert_data_content_t;
struct __e_acsl_assert_data_value_t {
   char const *name ;
   __e_acsl_assert_data_type_t type ;
   __e_acsl_assert_data_content_t content ;
   struct __e_acsl_assert_data_value_t *next ;
};
typedef struct __e_acsl_assert_data_value_t __attribute__((__FC_BUILTIN__)) __e_acsl_assert_data_value_t;
struct __e_acsl_assert_data_t {
   int blocking ;
   char const *kind ;
   char const *name ;
   char const *pred_txt ;
   char const *file ;
   char const *fct ;
   int line ;
   __e_acsl_assert_data_value_t *values ;
};
typedef struct __e_acsl_assert_data_t __attribute__((__FC_BUILTIN__)) __e_acsl_assert_data_t;
struct __e_acsl_contract_t;
typedef struct __e_acsl_contract_t __attribute__((__FC_BUILTIN__)) __e_acsl_contract_t;
/*@ ghost extern int __e_acsl_init; */

/*@ requires \valid_read(data) ∧ \initialized(data);
    assigns \nothing;
    
    behavior blocking:
      assumes data->blocking ≢ 0;
      requires predicate ≢ 0;
    
    behavior non_blocking:
      assumes data->blocking ≡ 0;
      check requires predicate ≢ 0;
    
    complete behaviors non_blocking, blocking;
    disjoint behaviors non_blocking, blocking;
 */
 __attribute__((__FC_BUILTIN__)) void __e_acsl_assert(int predicate,
                                                      __e_acsl_assert_data_t *data);

extern size_t __e_acsl_heap_allocation_size;

extern size_t __e_acsl_heap_allocated_blocks;

/*@ requires \valid(data);
    requires data->values ≡ \null ∨ \valid(data->values);
    assigns data->values;
    assigns data->values \from (indirect: __fc_heap_status), value;
 */
 __attribute__((__FC_BUILTIN__)) void __e_acsl_assert_register_int(__e_acsl_assert_data_t *data,
                                                                   char const *name,
                                                                   int is_enum,
                                                                   int value);

/*@ requires \valid(data);
    requires data->values ≡ \null ∨ \valid(data->values);
    assigns data->values;
    assigns data->values \from (indirect: __fc_heap_status), value;
 */
 __attribute__((__FC_BUILTIN__)) void __e_acsl_assert_register_ulong(
                                                                    __e_acsl_assert_data_t *data,
                                                                    char const *name,
                                                                    int is_enum,
                                                                    unsigned long value);

/*@ requires \valid(data);
    requires data->values ≡ \null ∨ \valid(data->values);
    assigns data->values;
    assigns data->values \from (indirect: __fc_heap_status), ptr;
 */
 __attribute__((__FC_BUILTIN__)) void __e_acsl_assert_register_ptr(__e_acsl_assert_data_t *data,
                                                                   char const *name,
                                                                   void *ptr);

/*@ requires \valid(data);
    assigns \nothing; */
 __attribute__((__FC_BUILTIN__)) void __e_acsl_assert_clean(__e_acsl_assert_data_t *data);

/*@ ensures \result ≡ \old(ptr);
    assigns \result;
    assigns \result \from *((char *)ptr + (0 .. size - 1)), ptr, size;
 */
 __attribute__((__FC_BUILTIN__)) void *__e_acsl_store_block(void *ptr,
                                                            size_t size);

/*@ assigns \nothing; */
 __attribute__((__FC_BUILTIN__)) void __e_acsl_delete_block(void *ptr);

/*@ assigns \nothing; */
 __attribute__((__FC_BUILTIN__)) void __e_acsl_initialize(void *ptr,
                                                          size_t size);

/*@ assigns \result;
    assigns \result \from *((char *)ptr + (0 .. size - 1)), ptr, size;
    
    behavior valid:
      assumes \valid((char *)ptr + (0 .. size - 1));
      assumes
        size ≤ 0 ∨
        ¬\separated(
            (char *)ptr + (0 .. size - 1),
            (char *)\base_addr(base) + (0 .. \block_length(base) - 1)
            );
      ensures \result ≡ 1;
    
    behavior invalid_ptr:
      assumes ¬\valid((char *)ptr + (0 .. size - 1));
      ensures \result ≡ 0;
    
    behavior separated_ptr:
      assumes size > 0;
      assumes
        \separated(
          (char *)ptr + (0 .. size - 1),
          (char *)\base_addr(base) + (0 .. \block_length(base) - 1)
          );
      ensures \result ≡ 0;
    
    complete behaviors separated_ptr, invalid_ptr, valid;
    disjoint behaviors separated_ptr, invalid_ptr, valid;
 */
 __attribute__((__FC_BUILTIN__)) int __e_acsl_valid(void *ptr, size_t size,
                                                    void *base,
                                                    void *addrof_base);

/*@ assigns \result;
    assigns \result \from *((char *)ptr + (0 .. size - 1)), ptr, size;
    
    behavior valid:
      assumes \valid_read((char *)ptr + (0 .. size - 1));
      assumes
        size ≤ 0 ∨
        ¬\separated(
            (char *)ptr + (0 .. size - 1),
            (char *)\base_addr(base) + (0 .. \block_length(base) - 1)
            );
      ensures \result ≡ 1;
    
    behavior invalid_ptr:
      assumes ¬\valid_read((char *)ptr + (0 .. size - 1));
      ensures \result ≡ 0;
    
    behavior separated_ptr:
      assumes size > 0;
      assumes
        \separated(
          (char *)ptr + (0 .. size - 1),
          (char *)\base_addr(base) + (0 .. \block_length(base) - 1)
          );
      ensures \result ≡ 0;
    
    complete behaviors separated_ptr, invalid_ptr, valid;
    disjoint behaviors separated_ptr, invalid_ptr, valid;
 */
 __attribute__((__FC_BUILTIN__)) int __e_acsl_valid_read(void *ptr,
                                                         size_t size,
                                                         void *base,
                                                         void *addrof_base);

long valid_nstring(char *s, long n, int wrtbl);

long valid_nwstring(wchar_t *s, long n, int wrtbl);

__inline static long valid_string__fc_inline(char *s, int wrtbl)
{
  long tmp;
  tmp = valid_nstring(s,(long)(-1),wrtbl);
  return tmp;
}

__inline static long valid_wstring__fc_inline(wchar_t *s, int wrtbl)
{
  long tmp;
  tmp = valid_nwstring(s,(long)(-1),wrtbl);
  return tmp;
}

extern  __attribute__((__FC_BUILTIN__)) int __e_acsl_sound_verdict;

/*@ requires l ≥ 0 ∧ l ≤ 5;
    requires \valid(table + 10);
    requires ∀ int j; 0 ≤ j < l ⇒ -100 ≤ *(table + j) ≤ 100;
    ensures
      ∀ int i, int j;
        0 ≤ i ≤ j < \old(l) ⇒ *(\old(table) + i) ≤ *(\old(table) + j);
 */
void __gen_e_acsl_testme(int *table, int l);

void testme(int *table, int l)
{
  int i;
  int temp;
  __e_acsl_store_block((void *)(& table),8UL);
  int nb = 0;
  char fini = (char)0;
  {
    int __gen_e_acsl_forall;
    int __gen_e_acsl_k;
    int __gen_e_acsl_and;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data = {.values = (void *)0};
    __gen_e_acsl_forall = 1;
    __gen_e_acsl_k = 0;
    while (1) {
      if (__gen_e_acsl_k < i) ; else break;
      {
        int __gen_e_acsl_valid_read;
        int __gen_e_acsl_valid_read_2;
        __e_acsl_assert_data_t __gen_e_acsl_assert_data_2 =
          {.values = (void *)0};
        __gen_e_acsl_valid_read = __e_acsl_valid_read((void *)(table + (
                                                               __gen_e_acsl_k + 1L)),
                                                      sizeof(int),
                                                      (void *)table,
                                                      (void *)(& table));
        __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_2,"table",
                                     (void *)table);
        __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_2,
                                     "__gen_e_acsl_k",0,__gen_e_acsl_k);
        __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_2,
                                       "sizeof(int)",0,sizeof(int));
        __gen_e_acsl_assert_data_2.blocking = 1;
        __gen_e_acsl_assert_data_2.kind = "RTE";
        __gen_e_acsl_assert_data_2.pred_txt = "\\valid_read(table + (long)(__gen_e_acsl_k + 1))";
        __gen_e_acsl_assert_data_2.file = "troubleshoot.c";
        __gen_e_acsl_assert_data_2.fct = "testme";
        __gen_e_acsl_assert_data_2.line = 10;
        __gen_e_acsl_assert_data_2.name = "mem_access";
        __e_acsl_assert(__gen_e_acsl_valid_read,& __gen_e_acsl_assert_data_2);
        __e_acsl_assert_clean(& __gen_e_acsl_assert_data_2);
        __e_acsl_assert_data_t __gen_e_acsl_assert_data_3 =
          {.values = (void *)0};
        __gen_e_acsl_valid_read_2 = __e_acsl_valid_read((void *)(table + __gen_e_acsl_k),
                                                        sizeof(int),
                                                        (void *)table,
                                                        (void *)(& table));
        __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_3,"table",
                                     (void *)table);
        __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_3,
                                     "__gen_e_acsl_k",0,__gen_e_acsl_k);
        __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_3,
                                       "sizeof(int)",0,sizeof(int));
        __gen_e_acsl_assert_data_3.blocking = 1;
        __gen_e_acsl_assert_data_3.kind = "RTE";
        __gen_e_acsl_assert_data_3.pred_txt = "\\valid_read(table + __gen_e_acsl_k)";
        __gen_e_acsl_assert_data_3.file = "troubleshoot.c";
        __gen_e_acsl_assert_data_3.fct = "testme";
        __gen_e_acsl_assert_data_3.line = 10;
        __gen_e_acsl_assert_data_3.name = "mem_access";
        __e_acsl_assert(__gen_e_acsl_valid_read_2,
                        & __gen_e_acsl_assert_data_3);
        __e_acsl_assert_clean(& __gen_e_acsl_assert_data_3);
        if (*(table + __gen_e_acsl_k) <= *(table + (__gen_e_acsl_k + 1L))) 
          ;
        else {
          __gen_e_acsl_forall = 0;
          goto e_acsl_end_loop1;
        }
      }
      __gen_e_acsl_k ++;
    }
    e_acsl_end_loop1: ;
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data,
                                 "\342\210\200 int k; 0 \342\211\244 k < i \342\207\222 *(table + k) \342\211\244 *(table + (k + 1))",
                                 0,__gen_e_acsl_forall);
    __gen_e_acsl_assert_data.blocking = 1;
    __gen_e_acsl_assert_data.kind = "Invariant";
    __gen_e_acsl_assert_data.pred_txt = "\342\210\200 int k; 0 \342\211\244 k < i \342\207\222 *(table + k) \342\211\244 *(table + (k + 1))";
    __gen_e_acsl_assert_data.file = "troubleshoot.c";
    __gen_e_acsl_assert_data.fct = "testme";
    __gen_e_acsl_assert_data.line = 10;
    __e_acsl_assert(__gen_e_acsl_forall,& __gen_e_acsl_assert_data);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data);
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_4 =
      {.values = (void *)0};
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,"nb",0,nb);
    if (0 <= nb) {
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,"nb",0,nb);
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,"l",0,l);
      __gen_e_acsl_and = nb < l;
    }
    else __gen_e_acsl_and = 0;
    __gen_e_acsl_assert_data_4.blocking = 1;
    __gen_e_acsl_assert_data_4.kind = "Invariant";
    __gen_e_acsl_assert_data_4.pred_txt = "0 \342\211\244 nb < l";
    __gen_e_acsl_assert_data_4.file = "troubleshoot.c";
    __gen_e_acsl_assert_data_4.fct = "testme";
    __gen_e_acsl_assert_data_4.line = 9;
    __e_acsl_assert(__gen_e_acsl_and,& __gen_e_acsl_assert_data_4);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_4);
  }
  /*@ loop invariant 0 ≤ nb < l;
      loop invariant
        ∀ int k; 0 ≤ k < i ⇒ *(table + k) ≤ *(table + (k + 1));
      loop assigns i, temp, nb, fini, *(table + (0 .. l - 1));
  */
  while (1) {
    if (! fini) {
      if (! (nb < l - 1)) break;
    }
    else break;
    {
      int __gen_e_acsl_and_4;
      int __gen_e_acsl_forall_4;
      int __gen_e_acsl_k_4;
      fini = (char)1;
      i = 0;
      {
        int __gen_e_acsl_forall_2;
        int __gen_e_acsl_k_2;
        int __gen_e_acsl_and_2;
        __e_acsl_assert_data_t __gen_e_acsl_assert_data_5 =
          {.values = (void *)0};
        __gen_e_acsl_forall_2 = 1;
        __gen_e_acsl_k_2 = 0;
        while (1) {
          if (__gen_e_acsl_k_2 < i) ; else break;
          {
            int __gen_e_acsl_valid_read_3;
            int __gen_e_acsl_valid_read_4;
            __e_acsl_assert_data_t __gen_e_acsl_assert_data_6 =
              {.values = (void *)0};
            __gen_e_acsl_valid_read_3 = __e_acsl_valid_read((void *)(
                                                            table + (
                                                            __gen_e_acsl_k_2 + 1L)),
                                                            sizeof(int),
                                                            (void *)table,
                                                            (void *)(& table));
            __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_6,
                                         "table",(void *)table);
            __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_6,
                                         "__gen_e_acsl_k_2",0,
                                         __gen_e_acsl_k_2);
            __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_6,
                                           "sizeof(int)",0,sizeof(int));
            __gen_e_acsl_assert_data_6.blocking = 1;
            __gen_e_acsl_assert_data_6.kind = "RTE";
            __gen_e_acsl_assert_data_6.pred_txt = "\\valid_read(table + (long)(__gen_e_acsl_k_2 + 1))";
            __gen_e_acsl_assert_data_6.file = "troubleshoot.c";
            __gen_e_acsl_assert_data_6.fct = "testme";
            __gen_e_acsl_assert_data_6.line = 16;
            __gen_e_acsl_assert_data_6.name = "mem_access";
            __e_acsl_assert(__gen_e_acsl_valid_read_3,
                            & __gen_e_acsl_assert_data_6);
            __e_acsl_assert_clean(& __gen_e_acsl_assert_data_6);
            __e_acsl_assert_data_t __gen_e_acsl_assert_data_7 =
              {.values = (void *)0};
            __gen_e_acsl_valid_read_4 = __e_acsl_valid_read((void *)(
                                                            table + __gen_e_acsl_k_2),
                                                            sizeof(int),
                                                            (void *)table,
                                                            (void *)(& table));
            __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_7,
                                         "table",(void *)table);
            __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_7,
                                         "__gen_e_acsl_k_2",0,
                                         __gen_e_acsl_k_2);
            __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_7,
                                           "sizeof(int)",0,sizeof(int));
            __gen_e_acsl_assert_data_7.blocking = 1;
            __gen_e_acsl_assert_data_7.kind = "RTE";
            __gen_e_acsl_assert_data_7.pred_txt = "\\valid_read(table + __gen_e_acsl_k_2)";
            __gen_e_acsl_assert_data_7.file = "troubleshoot.c";
            __gen_e_acsl_assert_data_7.fct = "testme";
            __gen_e_acsl_assert_data_7.line = 16;
            __gen_e_acsl_assert_data_7.name = "mem_access";
            __e_acsl_assert(__gen_e_acsl_valid_read_4,
                            & __gen_e_acsl_assert_data_7);
            __e_acsl_assert_clean(& __gen_e_acsl_assert_data_7);
            if (*(table + __gen_e_acsl_k_2) <= *(table + (__gen_e_acsl_k_2 + 1L))) 
              ;
            else {
              __gen_e_acsl_forall_2 = 0;
              goto e_acsl_end_loop2;
            }
          }
          __gen_e_acsl_k_2 ++;
        }
        e_acsl_end_loop2: ;
        __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_5,
                                     "\342\210\200 int k; 0 \342\211\244 k < i \342\207\222 *(table + k) \342\211\244 *(table + (k + 1))",
                                     0,__gen_e_acsl_forall_2);
        __gen_e_acsl_assert_data_5.blocking = 1;
        __gen_e_acsl_assert_data_5.kind = "Invariant";
        __gen_e_acsl_assert_data_5.pred_txt = "\342\210\200 int k; 0 \342\211\244 k < i \342\207\222 *(table + k) \342\211\244 *(table + (k + 1))";
        __gen_e_acsl_assert_data_5.file = "troubleshoot.c";
        __gen_e_acsl_assert_data_5.fct = "testme";
        __gen_e_acsl_assert_data_5.line = 16;
        __e_acsl_assert(__gen_e_acsl_forall_2,& __gen_e_acsl_assert_data_5);
        __e_acsl_assert_clean(& __gen_e_acsl_assert_data_5);
        __e_acsl_assert_data_t __gen_e_acsl_assert_data_8 =
          {.values = (void *)0};
        __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_8,"i",0,i);
        if (0 <= i) {
          __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_8,"i",0,i);
          __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_8,"l",0,l);
          __gen_e_acsl_and_2 = i < l;
        }
        else __gen_e_acsl_and_2 = 0;
        __gen_e_acsl_assert_data_8.blocking = 1;
        __gen_e_acsl_assert_data_8.kind = "Invariant";
        __gen_e_acsl_assert_data_8.pred_txt = "0 \342\211\244 i < l";
        __gen_e_acsl_assert_data_8.file = "troubleshoot.c";
        __gen_e_acsl_assert_data_8.fct = "testme";
        __gen_e_acsl_assert_data_8.line = 15;
        __e_acsl_assert(__gen_e_acsl_and_2,& __gen_e_acsl_assert_data_8);
        __e_acsl_assert_clean(& __gen_e_acsl_assert_data_8);
      }
      /*@ loop invariant 0 ≤ i < l;
          loop invariant
            ∀ int k; 0 ≤ k < i ⇒ *(table + k) ≤ *(table + (k + 1));
          loop assigns i, temp, *(table + (0 .. l - 1));
      */
      while (i < l - 1) {
        if (*(table + i) > *(table + (i + 1))) {
          fini = (char)0;
          temp = *(table + i);
          __e_acsl_initialize((void *)(table + i),sizeof(int));
          *(table + i) = *(table + (i + 1));
          __e_acsl_initialize((void *)(table + (i + 1)),sizeof(int));
          *(table + (i + 1)) = temp;
        }
        {
          int __gen_e_acsl_and_3;
          int __gen_e_acsl_forall_3;
          int __gen_e_acsl_k_3;
          i ++;
          __e_acsl_assert_data_t __gen_e_acsl_assert_data_9 =
            {.values = (void *)0};
          __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_9,"i",0,i);
          if (0 <= i) {
            __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_9,"i",0,
                                         i);
            __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_9,"l",0,
                                         l);
            __gen_e_acsl_and_3 = i < l;
          }
          else __gen_e_acsl_and_3 = 0;
          __gen_e_acsl_assert_data_9.blocking = 1;
          __gen_e_acsl_assert_data_9.kind = "Invariant";
          __gen_e_acsl_assert_data_9.pred_txt = "0 \342\211\244 i < l";
          __gen_e_acsl_assert_data_9.file = "troubleshoot.c";
          __gen_e_acsl_assert_data_9.fct = "testme";
          __gen_e_acsl_assert_data_9.line = 15;
          __e_acsl_assert(__gen_e_acsl_and_3,& __gen_e_acsl_assert_data_9);
          __e_acsl_assert_clean(& __gen_e_acsl_assert_data_9);
          __e_acsl_assert_data_t __gen_e_acsl_assert_data_10 =
            {.values = (void *)0};
          __gen_e_acsl_forall_3 = 1;
          __gen_e_acsl_k_3 = 0;
          while (1) {
            if (__gen_e_acsl_k_3 < i) ; else break;
            {
              int __gen_e_acsl_valid_read_5;
              int __gen_e_acsl_valid_read_6;
              __e_acsl_assert_data_t __gen_e_acsl_assert_data_11 =
                {.values = (void *)0};
              __gen_e_acsl_valid_read_5 = __e_acsl_valid_read((void *)(
                                                              table + (
                                                              __gen_e_acsl_k_3 + 1L)),
                                                              sizeof(int),
                                                              (void *)table,
                                                              (void *)(& table));
              __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_11,
                                           "table",(void *)table);
              __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_11,
                                           "__gen_e_acsl_k_3",0,
                                           __gen_e_acsl_k_3);
              __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_11,
                                             "sizeof(int)",0,sizeof(int));
              __gen_e_acsl_assert_data_11.blocking = 1;
              __gen_e_acsl_assert_data_11.kind = "RTE";
              __gen_e_acsl_assert_data_11.pred_txt = "\\valid_read(table + (long)(__gen_e_acsl_k_3 + 1))";
              __gen_e_acsl_assert_data_11.file = "troubleshoot.c";
              __gen_e_acsl_assert_data_11.fct = "testme";
              __gen_e_acsl_assert_data_11.line = 16;
              __gen_e_acsl_assert_data_11.name = "mem_access";
              __e_acsl_assert(__gen_e_acsl_valid_read_5,
                              & __gen_e_acsl_assert_data_11);
              __e_acsl_assert_clean(& __gen_e_acsl_assert_data_11);
              __e_acsl_assert_data_t __gen_e_acsl_assert_data_12 =
                {.values = (void *)0};
              __gen_e_acsl_valid_read_6 = __e_acsl_valid_read((void *)(
                                                              table + __gen_e_acsl_k_3),
                                                              sizeof(int),
                                                              (void *)table,
                                                              (void *)(& table));
              __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_12,
                                           "table",(void *)table);
              __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_12,
                                           "__gen_e_acsl_k_3",0,
                                           __gen_e_acsl_k_3);
              __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_12,
                                             "sizeof(int)",0,sizeof(int));
              __gen_e_acsl_assert_data_12.blocking = 1;
              __gen_e_acsl_assert_data_12.kind = "RTE";
              __gen_e_acsl_assert_data_12.pred_txt = "\\valid_read(table + __gen_e_acsl_k_3)";
              __gen_e_acsl_assert_data_12.file = "troubleshoot.c";
              __gen_e_acsl_assert_data_12.fct = "testme";
              __gen_e_acsl_assert_data_12.line = 16;
              __gen_e_acsl_assert_data_12.name = "mem_access";
              __e_acsl_assert(__gen_e_acsl_valid_read_6,
                              & __gen_e_acsl_assert_data_12);
              __e_acsl_assert_clean(& __gen_e_acsl_assert_data_12);
              if (*(table + __gen_e_acsl_k_3) <= *(table + (__gen_e_acsl_k_3 + 1L))) 
                ;
              else {
                __gen_e_acsl_forall_3 = 0;
                goto e_acsl_end_loop3;
              }
            }
            __gen_e_acsl_k_3 ++;
          }
          e_acsl_end_loop3: ;
          __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_10,
                                       "\342\210\200 int k; 0 \342\211\244 k < i \342\207\222 *(table + k) \342\211\244 *(table + (k + 1))",
                                       0,__gen_e_acsl_forall_3);
          __gen_e_acsl_assert_data_10.blocking = 1;
          __gen_e_acsl_assert_data_10.kind = "Invariant";
          __gen_e_acsl_assert_data_10.pred_txt = "\342\210\200 int k; 0 \342\211\244 k < i \342\207\222 *(table + k) \342\211\244 *(table + (k + 1))";
          __gen_e_acsl_assert_data_10.file = "troubleshoot.c";
          __gen_e_acsl_assert_data_10.fct = "testme";
          __gen_e_acsl_assert_data_10.line = 16;
          __e_acsl_assert(__gen_e_acsl_forall_3,
                          & __gen_e_acsl_assert_data_10);
          __e_acsl_assert_clean(& __gen_e_acsl_assert_data_10);
        }
      }
      nb ++;
      __e_acsl_assert_data_t __gen_e_acsl_assert_data_13 =
        {.values = (void *)0};
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_13,"nb",0,nb);
      if (0 <= nb) {
        __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_13,"nb",0,nb);
        __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_13,"l",0,l);
        __gen_e_acsl_and_4 = nb < l;
      }
      else __gen_e_acsl_and_4 = 0;
      __gen_e_acsl_assert_data_13.blocking = 1;
      __gen_e_acsl_assert_data_13.kind = "Invariant";
      __gen_e_acsl_assert_data_13.pred_txt = "0 \342\211\244 nb < l";
      __gen_e_acsl_assert_data_13.file = "troubleshoot.c";
      __gen_e_acsl_assert_data_13.fct = "testme";
      __gen_e_acsl_assert_data_13.line = 9;
      __e_acsl_assert(__gen_e_acsl_and_4,& __gen_e_acsl_assert_data_13);
      __e_acsl_assert_clean(& __gen_e_acsl_assert_data_13);
      __e_acsl_assert_data_t __gen_e_acsl_assert_data_14 =
        {.values = (void *)0};
      __gen_e_acsl_forall_4 = 1;
      __gen_e_acsl_k_4 = 0;
      while (1) {
        if (__gen_e_acsl_k_4 < i) ; else break;
        {
          int __gen_e_acsl_valid_read_7;
          int __gen_e_acsl_valid_read_8;
          __e_acsl_assert_data_t __gen_e_acsl_assert_data_15 =
            {.values = (void *)0};
          __gen_e_acsl_valid_read_7 = __e_acsl_valid_read((void *)(table + (
                                                                   __gen_e_acsl_k_4 + 1L)),
                                                          sizeof(int),
                                                          (void *)table,
                                                          (void *)(& table));
          __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_15,"table",
                                       (void *)table);
          __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_15,
                                       "__gen_e_acsl_k_4",0,__gen_e_acsl_k_4);
          __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_15,
                                         "sizeof(int)",0,sizeof(int));
          __gen_e_acsl_assert_data_15.blocking = 1;
          __gen_e_acsl_assert_data_15.kind = "RTE";
          __gen_e_acsl_assert_data_15.pred_txt = "\\valid_read(table + (long)(__gen_e_acsl_k_4 + 1))";
          __gen_e_acsl_assert_data_15.file = "troubleshoot.c";
          __gen_e_acsl_assert_data_15.fct = "testme";
          __gen_e_acsl_assert_data_15.line = 10;
          __gen_e_acsl_assert_data_15.name = "mem_access";
          __e_acsl_assert(__gen_e_acsl_valid_read_7,
                          & __gen_e_acsl_assert_data_15);
          __e_acsl_assert_clean(& __gen_e_acsl_assert_data_15);
          __e_acsl_assert_data_t __gen_e_acsl_assert_data_16 =
            {.values = (void *)0};
          __gen_e_acsl_valid_read_8 = __e_acsl_valid_read((void *)(table + __gen_e_acsl_k_4),
                                                          sizeof(int),
                                                          (void *)table,
                                                          (void *)(& table));
          __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_16,"table",
                                       (void *)table);
          __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_16,
                                       "__gen_e_acsl_k_4",0,__gen_e_acsl_k_4);
          __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_16,
                                         "sizeof(int)",0,sizeof(int));
          __gen_e_acsl_assert_data_16.blocking = 1;
          __gen_e_acsl_assert_data_16.kind = "RTE";
          __gen_e_acsl_assert_data_16.pred_txt = "\\valid_read(table + __gen_e_acsl_k_4)";
          __gen_e_acsl_assert_data_16.file = "troubleshoot.c";
          __gen_e_acsl_assert_data_16.fct = "testme";
          __gen_e_acsl_assert_data_16.line = 10;
          __gen_e_acsl_assert_data_16.name = "mem_access";
          __e_acsl_assert(__gen_e_acsl_valid_read_8,
                          & __gen_e_acsl_assert_data_16);
          __e_acsl_assert_clean(& __gen_e_acsl_assert_data_16);
          if (*(table + __gen_e_acsl_k_4) <= *(table + (__gen_e_acsl_k_4 + 1L))) 
            ;
          else {
            __gen_e_acsl_forall_4 = 0;
            goto e_acsl_end_loop4;
          }
        }
        __gen_e_acsl_k_4 ++;
      }
      e_acsl_end_loop4: ;
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_14,
                                   "\342\210\200 int k; 0 \342\211\244 k < i \342\207\222 *(table + k) \342\211\244 *(table + (k + 1))",
                                   0,__gen_e_acsl_forall_4);
      __gen_e_acsl_assert_data_14.blocking = 1;
      __gen_e_acsl_assert_data_14.kind = "Invariant";
      __gen_e_acsl_assert_data_14.pred_txt = "\342\210\200 int k; 0 \342\211\244 k < i \342\207\222 *(table + k) \342\211\244 *(table + (k + 1))";
      __gen_e_acsl_assert_data_14.file = "troubleshoot.c";
      __gen_e_acsl_assert_data_14.fct = "testme";
      __gen_e_acsl_assert_data_14.line = 10;
      __e_acsl_assert(__gen_e_acsl_forall_4,& __gen_e_acsl_assert_data_14);
      __e_acsl_assert_clean(& __gen_e_acsl_assert_data_14);
    }
  }
  __e_acsl_delete_block((void *)(& table));
  return;
}

/*@ requires l ≥ 0 ∧ l ≤ 5;
    requires \valid(table + 10);
    requires ∀ int j; 0 ≤ j < l ⇒ -100 ≤ *(table + j) ≤ 100;
    ensures
      ∀ int i, int j;
        0 ≤ i ≤ j < \old(l) ⇒ *(\old(table) + i) ≤ *(\old(table) + j);
 */
void __gen_e_acsl_testme(int *table, int l)
{
  int __gen_e_acsl_at_2;
  int *__gen_e_acsl_at;
  {
    int __gen_e_acsl_and;
    int __gen_e_acsl_valid;
    int __gen_e_acsl_forall;
    int __gen_e_acsl_j;
    __gen_e_acsl_at = table;
    __gen_e_acsl_at_2 = l;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data = {.values = (void *)0};
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data,"l",0,l);
    if (l >= 0) {
      __e_acsl_assert_register_int(& __gen_e_acsl_assert_data,"l",0,l);
      __gen_e_acsl_and = l <= 5;
    }
    else __gen_e_acsl_and = 0;
    __gen_e_acsl_assert_data.blocking = 1;
    __gen_e_acsl_assert_data.kind = "Precondition";
    __gen_e_acsl_assert_data.pred_txt = "l \342\211\245 0 \342\210\247 l \342\211\244 5";
    __gen_e_acsl_assert_data.file = "troubleshoot.c";
    __gen_e_acsl_assert_data.fct = "testme";
    __gen_e_acsl_assert_data.line = 1;
    __e_acsl_assert(__gen_e_acsl_and,& __gen_e_acsl_assert_data);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data);
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_2 =
      {.values = (void *)0};
    __gen_e_acsl_valid = __e_acsl_valid((void *)(table + 10),sizeof(int),
                                        (void *)table,(void *)(& table));
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_2,"table",
                                 (void *)table);
    __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_2,
                                   "sizeof(int)",0,sizeof(int));
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_2,
                                 "\\valid(table + 10)",0,__gen_e_acsl_valid);
    __gen_e_acsl_assert_data_2.blocking = 1;
    __gen_e_acsl_assert_data_2.kind = "Precondition";
    __gen_e_acsl_assert_data_2.pred_txt = "\\valid(table + 10)";
    __gen_e_acsl_assert_data_2.file = "troubleshoot.c";
    __gen_e_acsl_assert_data_2.fct = "testme";
    __gen_e_acsl_assert_data_2.line = 2;
    __e_acsl_assert(__gen_e_acsl_valid,& __gen_e_acsl_assert_data_2);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_2);
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_3 =
      {.values = (void *)0};
    __gen_e_acsl_forall = 1;
    __gen_e_acsl_j = 0;
    while (1) {
      if (__gen_e_acsl_j < l) ; else break;
      {
        int __gen_e_acsl_valid_read;
        int __gen_e_acsl_and_2;
        __e_acsl_assert_data_t __gen_e_acsl_assert_data_4 =
          {.values = (void *)0};
        __gen_e_acsl_valid_read = __e_acsl_valid_read((void *)(table + __gen_e_acsl_j),
                                                      sizeof(int),
                                                      (void *)table,
                                                      (void *)(& table));
        __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_4,"table",
                                     (void *)table);
        __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,
                                     "__gen_e_acsl_j",0,__gen_e_acsl_j);
        __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_4,
                                       "sizeof(int)",0,sizeof(int));
        __gen_e_acsl_assert_data_4.blocking = 1;
        __gen_e_acsl_assert_data_4.kind = "RTE";
        __gen_e_acsl_assert_data_4.pred_txt = "\\valid_read(table + __gen_e_acsl_j)";
        __gen_e_acsl_assert_data_4.file = "troubleshoot.c";
        __gen_e_acsl_assert_data_4.fct = "testme";
        __gen_e_acsl_assert_data_4.line = 3;
        __gen_e_acsl_assert_data_4.name = "mem_access";
        __e_acsl_assert(__gen_e_acsl_valid_read,& __gen_e_acsl_assert_data_4);
        __e_acsl_assert_clean(& __gen_e_acsl_assert_data_4);
        if (-100 <= *(table + __gen_e_acsl_j)) {
          int __gen_e_acsl_valid_read_2;
          __e_acsl_assert_data_t __gen_e_acsl_assert_data_5 =
            {.values = (void *)0};
          __gen_e_acsl_valid_read_2 = __e_acsl_valid_read((void *)(table + __gen_e_acsl_j),
                                                          sizeof(int),
                                                          (void *)table,
                                                          (void *)(& table));
          __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_5,"table",
                                       (void *)table);
          __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_5,
                                       "__gen_e_acsl_j",0,__gen_e_acsl_j);
          __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_5,
                                         "sizeof(int)",0,sizeof(int));
          __gen_e_acsl_assert_data_5.blocking = 1;
          __gen_e_acsl_assert_data_5.kind = "RTE";
          __gen_e_acsl_assert_data_5.pred_txt = "\\valid_read(table + __gen_e_acsl_j)";
          __gen_e_acsl_assert_data_5.file = "troubleshoot.c";
          __gen_e_acsl_assert_data_5.fct = "testme";
          __gen_e_acsl_assert_data_5.line = 3;
          __gen_e_acsl_assert_data_5.name = "mem_access";
          __e_acsl_assert(__gen_e_acsl_valid_read_2,
                          & __gen_e_acsl_assert_data_5);
          __e_acsl_assert_clean(& __gen_e_acsl_assert_data_5);
          __gen_e_acsl_and_2 = *(table + __gen_e_acsl_j) <= 100;
        }
        else __gen_e_acsl_and_2 = 0;
        if (__gen_e_acsl_and_2) ;
        else {
          __gen_e_acsl_forall = 0;
          goto e_acsl_end_loop5;
        }
      }
      __gen_e_acsl_j ++;
    }
    e_acsl_end_loop5: ;
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_3,
                                 "\342\210\200 int j; 0 \342\211\244 j < l \342\207\222 -100 \342\211\244 *(table + j) \342\211\244 100",
                                 0,__gen_e_acsl_forall);
    __gen_e_acsl_assert_data_3.blocking = 1;
    __gen_e_acsl_assert_data_3.kind = "Precondition";
    __gen_e_acsl_assert_data_3.pred_txt = "\342\210\200 int j; 0 \342\211\244 j < l \342\207\222 -100 \342\211\244 *(table + j) \342\211\244 100";
    __gen_e_acsl_assert_data_3.file = "troubleshoot.c";
    __gen_e_acsl_assert_data_3.fct = "testme";
    __gen_e_acsl_assert_data_3.line = 3;
    __e_acsl_assert(__gen_e_acsl_forall,& __gen_e_acsl_assert_data_3);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_3);
  }
  testme(table,l);
  {
    int __gen_e_acsl_forall_2;
    int __gen_e_acsl_i;
    int __gen_e_acsl_j_2;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_6 =
      {.values = (void *)0};
    __gen_e_acsl_forall_2 = 1;
    __gen_e_acsl_i = 0;
    while (1) {
      if (__gen_e_acsl_i < l) ; else break;
      __gen_e_acsl_j_2 = __gen_e_acsl_i;
      while (1) {
        if (__gen_e_acsl_j_2 < l) ; else break;
        {
          int __gen_e_acsl_valid_read_3;
          int __gen_e_acsl_valid_read_4;
          __e_acsl_assert_data_t __gen_e_acsl_assert_data_7 =
            {.values = (void *)0};
          __gen_e_acsl_valid_read_3 = __e_acsl_valid_read((void *)(table + __gen_e_acsl_j_2),
                                                          sizeof(int),
                                                          (void *)table,
                                                          (void *)(& table));
          __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_7,"table",
                                       (void *)table);
          __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_7,
                                       "__gen_e_acsl_j_2",0,__gen_e_acsl_j_2);
          __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_7,
                                         "sizeof(int)",0,sizeof(int));
          __gen_e_acsl_assert_data_7.blocking = 1;
          __gen_e_acsl_assert_data_7.kind = "RTE";
          __gen_e_acsl_assert_data_7.pred_txt = "\\valid_read(table + __gen_e_acsl_j_2)";
          __gen_e_acsl_assert_data_7.file = "troubleshoot.c";
          __gen_e_acsl_assert_data_7.fct = "testme";
          __gen_e_acsl_assert_data_7.line = 4;
          __gen_e_acsl_assert_data_7.name = "mem_access";
          __e_acsl_assert(__gen_e_acsl_valid_read_3,
                          & __gen_e_acsl_assert_data_7);
          __e_acsl_assert_clean(& __gen_e_acsl_assert_data_7);
          __e_acsl_assert_data_t __gen_e_acsl_assert_data_8 =
            {.values = (void *)0};
          __gen_e_acsl_valid_read_4 = __e_acsl_valid_read((void *)(table + __gen_e_acsl_i),
                                                          sizeof(int),
                                                          (void *)table,
                                                          (void *)(& table));
          __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_8,"table",
                                       (void *)table);
          __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_8,
                                       "__gen_e_acsl_i",0,__gen_e_acsl_i);
          __e_acsl_assert_register_ulong(& __gen_e_acsl_assert_data_8,
                                         "sizeof(int)",0,sizeof(int));
          __gen_e_acsl_assert_data_8.blocking = 1;
          __gen_e_acsl_assert_data_8.kind = "RTE";
          __gen_e_acsl_assert_data_8.pred_txt = "\\valid_read(table + __gen_e_acsl_i)";
          __gen_e_acsl_assert_data_8.file = "troubleshoot.c";
          __gen_e_acsl_assert_data_8.fct = "testme";
          __gen_e_acsl_assert_data_8.line = 4;
          __gen_e_acsl_assert_data_8.name = "mem_access";
          __e_acsl_assert(__gen_e_acsl_valid_read_4,
                          & __gen_e_acsl_assert_data_8);
          __e_acsl_assert_clean(& __gen_e_acsl_assert_data_8);
          if (*(table + __gen_e_acsl_i) <= *(table + __gen_e_acsl_j_2)) 
            ;
          else {
            __gen_e_acsl_forall_2 = 0;
            goto e_acsl_end_loop6;
          }
        }
        __gen_e_acsl_j_2 ++;
      }
      __gen_e_acsl_i ++;
    }
    e_acsl_end_loop6: ;
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_6,
                                 "\342\210\200 int i, int j;\n  0 \342\211\244 i \342\211\244 j < \\old(l) \342\207\222 *(\\old(table) + i) \342\211\244 *(\\old(table) + j)",
                                 0,__gen_e_acsl_forall_2);
    __gen_e_acsl_assert_data_6.blocking = 1;
    __gen_e_acsl_assert_data_6.kind = "Postcondition";
    __gen_e_acsl_assert_data_6.pred_txt = "\342\210\200 int i, int j;\n  0 \342\211\244 i \342\211\244 j < \\old(l) \342\207\222 *(\\old(table) + i) \342\211\244 *(\\old(table) + j)";
    __gen_e_acsl_assert_data_6.file = "troubleshoot.c";
    __gen_e_acsl_assert_data_6.fct = "testme";
    __gen_e_acsl_assert_data_6.line = 4;
    __e_acsl_assert(__gen_e_acsl_forall_2,& __gen_e_acsl_assert_data_6);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_6);
    return;
  }
}


