/* Generated by Frama-C */
void pathcrawler_trace_full(char *format, char *comm , ...);

extern int pathcrawler_assert_exception(char *file, int line);

void __FC_assert(int c, char *file, int line, char const *cond)
{
  pathcrawler_assert_exception(file,line);
  return;
}

int Tritype(double i, double j, double k)
{
  int __retres;
  int trityp = 0;
  if (i < 0.0) {
    pathcrawler_trace_full("+243","l.10, file TriType.c");
    goto lin_ite_body_2;
  }
  else {
    pathcrawler_trace_full("-243","l.10, file TriType.c");
    if (j < 0.0) {
      pathcrawler_trace_full("+248","l.10, file TriType.c");
      goto lin_ite_body_2;
    }
    else {
      pathcrawler_trace_full("-248","l.10, file TriType.c");
      if (k < 0.0) {
        pathcrawler_trace_full("+251","l.10, file TriType.c");
        lin_ite_body_2: {
                          __retres = 3;
                          goto return_label;
                        }
      }
      else pathcrawler_trace_full("-251","l.10, file TriType.c");
    }
  }
  if (i + j <= k) {
    pathcrawler_trace_full("+257","l.12, file TriType.c");
    goto lin_ite_body_12;
  }
  else {
    pathcrawler_trace_full("-257","l.12, file TriType.c");
    if (j + k <= i) {
      pathcrawler_trace_full("+262","l.12, file TriType.c");
      goto lin_ite_body_12;
    }
    else {
      pathcrawler_trace_full("-262","l.12, file TriType.c");
      if (k + i <= j) {
        pathcrawler_trace_full("+265","l.12, file TriType.c");
        lin_ite_body_12: {
                           __retres = 3;
                           goto return_label;
                         }
      }
      else pathcrawler_trace_full("-265","l.12, file TriType.c");
    }
  }
  if (i == j) {
    pathcrawler_trace_full("+271","l.14, file TriType.c");
    lin_ite_body_22: trityp ++;
  }
  else {
    pathcrawler_trace_full("-271","l.14, file TriType.c");
    lin_ite_body_23: ;
  }
  if (i == k) {
    pathcrawler_trace_full("+276","l.15, file TriType.c");
    lin_ite_body_27: trityp ++;
  }
  else {
    pathcrawler_trace_full("-276","l.15, file TriType.c");
    lin_ite_body_28: ;
  }
  if (j == k) {
    pathcrawler_trace_full("+281","l.16, file TriType.c");
    lin_ite_body_32: trityp ++;
  }
  else {
    pathcrawler_trace_full("-281","l.16, file TriType.c");
    lin_ite_body_33: ;
  }
  if (trityp >= 2) {
    pathcrawler_trace_full("+286","l.17, file TriType.c");
    lin_ite_body_37: trityp = 2;
  }
  else {
    pathcrawler_trace_full("-286","l.17, file TriType.c");
    lin_ite_body_38: ;
  }
  __retres = trityp;
  return_label: return __retres;
}


